services:

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5000:5000"
  
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - REDIS_HOST=database
    ports:
      - "8080:8080"
  
  database:
    image: redis
    restart: unless-stopped