services:
  backend:
    build: 
      context: ./backend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: backend_test